spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=postgres
spring.datasource.password=Srikrishna192414

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081